---
- hosts: localhost
  vars:
    installer:  "{{ base_dir }}/bin/openshift-install --dir {{ stage_dir }}" 
  tasks:

    - name: Creates directory
      file:
        path:  "{{ stage_dir }}"
        state: directory

    - name: regen install-config 
      copy:
        src:  "{{ base_dir }}/files/install-config.yaml.orig"
        dest: "{{ stage_dir }}/install-config.yaml"

    - name: validate install-config
      command: "{{ installer }} create install-config"
      environment:
        OS_CLOUD: fsi-moc

    - name: adjust install config
      command: "{{ base_dir }}/bin/adjust_install_config.py"
      args:
        chdir:  "{{ base_dir }}/stage"

    - name: create manifests
      command: "{{ installer }} create manifests"
      environment:
         OS_CLOUD: fsi-moc

