---
- hosts: localhost
  vars:
    base_dir: /home/ayoung/ocp-ansible
  tasks:

    - name: Creates directory
      file:
        path:  "{{ stage_dir }}"
        state: directory

    - name: regen install-config 
      copy:
        src:  "{{ base_dir }}/files/install-config.yaml.orig"
        dest: "{{ stage_dir }}/install-config.yaml"

    - name: validate install-config
      command: "{{ base_dir }}/bin/openshift-install create install-config --dir {{ stage_dir }}"
      environment:
        OS_CLOUD: fsi-moc


